# Manipulating Arrays

Here are two techniques that can be used to change or manipulayte the structure of arrays:
*  Stacking
*  Reshaping

### Stacking

In [3]:
#importing the NumPy library
import numpy as np

# Creating two 1-D arrays with 5 elements using arange
arr_1 = np.arange(5)
arr_2 = np.arange(5, 10)


In [5]:
# Horizonal stacking - Appending the elements in the same row
np.hstack((arr_1,arr_2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Vertical stacking - Increasing the number of row


# Storing the stacked array for further operations
arr_3 = np.vstack((arr_1, arr_2))



In [12]:
# Checking the dimensions of the array
arr_3.ndim

2

In [13]:
# Printing the created array
arr_3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
# Number of rows and columns in the array
arr_3.shape

(2, 5)

### Reshaping

In [15]:
# Creating an array of first ten natural numbers
arr_4 = np.arange(1,11) 

# Printing the created array
arr_4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# Reshaping the 1D array into a 2D array with 2 elements in five rows
arr_5 = arr_4.reshape(5, 2)

In [17]:
# Checking the rows and columns in the created array
arr_5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [18]:
# Creating a 2D array with 4 elements in five rows (elements from 20 to 39)
arr_6 = np.arange(20, 40).reshape(5, 4)

# Checking the rows and columns in the created array
arr_6

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [20]:
# Stacking arr_5 and arr_6
np.vstack((arr_5, arr_6))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 4

In [21]:
# Check the structure of arr_6
arr_6.shape

(5, 4)

In [22]:
# Reshape the arr_6 to vertically stack with arr_5 
arr_6 = np.arange(20, 40).reshape(10, 2)
arr_6

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [23]:
# Stacking arr_5 and arr_6
np.vstack((arr_5, arr_6))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [28]:
arr_7 = np.arange(1,133).reshape(11, 12)

In [29]:
arr_7

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36],
       [ 37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48],
       [ 49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72],
       [ 73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96],
       [ 97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108],
       [109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132]])

In [30]:
arr_7.shape

(11, 12)

In [35]:
arr_7[8][3]

100

In [37]:
np.unravel_index(99, (11,12))

(8, 3)

In [38]:
p = [[1, 5],[3, 7],[4, 9]]

In [39]:
np.reshape(p, -1)

array([1, 5, 3, 7, 4, 9])

In [52]:
array_1 = np.arange(1,21).reshape(4,5)

array_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [53]:
print(array_1[array_1%2 != 0].reshape(5, 2))

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]


In [54]:

print(array_1[array_1%2 != 0].reshape(5, 2))


[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]


In [55]:
print(array_1[array_1%2 == 0].reshape(5, 2))

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]


In [56]:
print(array_1[array_1%2 != 0])

[ 1  3  5  7  9 11 13 15 17 19]


In [57]:
print(array_1.reshape(5, 4)[array_1%2 != 0])

ValueError: operands could not be broadcast together with shapes (5,4) (4,5) 

In [58]:
p = [[1, 5],
 [3, 7],
 [4, 9]]

np.reshape(p, (1, -1))

array([[1, 5, 3, 7, 4, 9]])