# Index of 50th element
Consider an (8, 8) shape NumPy array. What is the index (x,y) of the 50th element?

Note: For counting the elements go row-wise. For example, in the array,

[[1, 5, 9],

 [3, 0, 2]]

the 5th element would be '0'.

In [9]:
import numpy as np


In [10]:
x = np.zeros((8,8),dtype=int)

In [8]:
np.unravel_index(49, (8,8))

(6, 1)

Or

In [11]:
y = np.array(range(1, 65)) #range(1, 8*8+1)) 
z = y.reshape(8,8)
z

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [12]:
np.unravel_index(49, (8,8))

(6, 1)

# Slicing Arrays
Which of the following would extract all the first 3 rows of the last 5 columns in a given numpy 2D array ‘a’?

In [20]:
arr = np.array(range(1,65))
a = arr.reshape(8,8)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [21]:
a[ :3, :5 ]

array([[ 1,  2,  3,  4,  5],
       [ 9, 10, 11, 12, 13],
       [17, 18, 19, 20, 21]])

In [22]:
a[ :3 , 5: ] 

array([[ 6,  7,  8],
       [14, 15, 16],
       [22, 23, 24]])

In [23]:
a[ :3 , :-5 ]

array([[ 1,  2,  3],
       [ 9, 10, 11],
       [17, 18, 19]])

In [24]:
a[ :3 , -5: ] 

array([[ 4,  5,  6,  7,  8],
       [12, 13, 14, 15, 16],
       [20, 21, 22, 23, 24]])

# So Many Functions
What will the output of np.arange(1,16,2).reshape(4, 2) be?

In [25]:
new_arr = np.arange(1,16,2).reshape(4,2)

In [26]:
new_arr

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

# Print "+"
Description
Given a single positive odd integer 'n' greater than 2, create a NumPy array of size (n x n) with all zeros and ones such that the ones make a shape like '+'. The lines of the plus must be present at the middle row and column.



Hint: Start by creating a (n x n) array with all zeroes using the np.zeros() function and then fill in the ones at the appropriate indices. Use integer division (//) to access the middle rows and columns

In [70]:
# Read the input
n = int(input())

# Import the NumPy package
import numpy as np 

# Write your code here
a = np.zeros((n,n),dtype ='int')
mid = n//2
for i in range(n):
    if i == mid:
        a[i]=1
        a[:,mid]=1

print(a)

5
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


or 

In [71]:
n = int(input())

# Import the NumPy package
import numpy as np 

# Write your code here
a = np.zeros((n,n),dtype ='int')
a[n//2::-n//2,::] = 1
a[::,n//2::-n//2] = 1
print(a)

5
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]
