In [1]:
l=[1,4,7]

l*2.5

TypeError: can't multiply sequence by non-int of type 'float'

In [2]:
import numpy as np

np_l=np.array([1,4,7])
np_l*2.5

array([ 2.5, 10. , 17.5])

In [4]:
np.array([1,"jvc",False])

array(['1', 'jvc', 'False'], dtype='<U11')

In [5]:
list1 = [1, 4, 6]
list2 = [3, 6, 7]
list1 + list2

[1, 4, 6, 3, 6, 7]

In [6]:
np_1 = np.array([1, 4, 6])
np_2 = np.array([3, 6, 7])

np_1 + np_2

array([ 4, 10, 13])

In [9]:
import numpy as np

lst=[1, 7, 0, 6, 2, 5, 6]

arr = np.array(lst)

print("List:",lst)
print("Array:",arr)

List: [1, 7, 0, 6, 2, 5, 6]
Array: [1 7 0 6 2 5 6]


In [12]:
fs = np.array( [1.0, 2, 3.5, 0.2, True] )

print (type(fs))

<class 'numpy.ndarray'>


In [14]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]
array_1 = np.array(array_1)
print(array_1[:3])

[1 2 3]


In [15]:
print(array_1[2:-3])

[3 5 4 6 7 8]


In [16]:
print(array_1[::-2])

[2 5 7 4 3 1]


In [18]:
avg = price.mean()
avg

NameError: name 'price' is not defined

In [20]:
array_name = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))

In [22]:
array_name[ : , :2]

array([[21, 22],
       [11, 22],
       [43, 77]])

In [23]:

array_name[ : , :3]

array([[21, 22, 23],
       [11, 22, 33],
       [43, 77, 89]])

In [27]:
np_3 = np.ones(5)
np_3

array([1., 1., 1., 1., 1.])

In [40]:
array1 = (np.arange(1,11))*5

In [41]:
print(array1)

[ 5 10 15 20 25 30 35 40 45 50]


In [38]:
array_multipleof5 = array1*5

In [42]:
x = np.ones((5,5))
x[1: -1, 1: -1]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [44]:
import numpy as np

n=int(input())
x = np.zeros((n,n),dtype='int')

x[1::2,::2]=1
x[::2,1::2]=1

print(x)

4
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]
